from twython import Twython, TwythonError

APP_KEY = 'UQVGvAiVnMSJpqdefj44Jw'
# Acess token generated by twauth.py and hard coded in
ACCESS_TOKEN = 'AAAAAAAAAAAAAAAAAAAAABRMVwAAAAAAnE6%2F41mZ20HV2LVadOufnqih%2Fc8%3DAP8Dhd8DkaKCFhJ1Nn7ZedG5TmU54dRJ865U26ByLgU0oIlkuo'

# Our reference to the twitter api
twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)

tweets = twitter.cursor(twitter.search,q='sunset',geocode='41.8262,-71.4032,1km')

startid = next(tweets)['id_str'] # Keep track of the first id to check for repeats

for tweet in tweets:
    print tweet['user']['screen_name']
    if tweet['id_str'] == startid:
        break


