from twython import Twython, TwythonError, TwythonStreamer, streaming

APP_KEY = 'UQVGvAiVnMSJpqdefj44Jw'
APP_SECRET = 'b6umv07DoBcqswtRu14NhwbV6Pq9CprHTjQKnReUTo'
OAUTH_TOKEN = 'qWrOdOxbA8ghhaM6Ph8l1vDTb3JEe3ixAcaBXcABKQ'
OAUTH_TOKEN_SECRET = 'Whpti67hgtzXxtlUWluQQxHXfxK69IGqLHSTJsSuT8'

# Acess token generated by twauth.py and hard coded in
ACCESS_TOKEN = 'AAAAAAAAAAAAAAAAAAAAABRMVwAAAAAAnE6%2F41mZ20HV2LVadOufnqih%2Fc8%3DAP8Dhd8DkaKCFhJ1Nn7ZedG5TmU54dRJ865U26ByLgU0oIlkuo'

# Our reference to the twitter api
twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)
stream = TwythonStreamer(app_key=APP_KEY, app_secret=APP_SECRET, oauth_token=OAUTH_TOKEN, oauth_token_secret=OAUTH_TOKEN_SECRET)
filtered_stream = streaming.types.TwythonStreamerTypesStatuses(stream)

# Try to get the first 100 results from twitter

try:
    tweets = twitter.search(q='#hackatbrown',geocode='41.8294833,-71.4021500,1km',result_type='recent', count=10)
except TwythonError as e:
    print e

# Print out the usernames of the tweets
for tweet in tweets['statuses']:
    print tweet['user']['screen_name'].encode('utf-8')
    print tweet['text'].encode('utf-8')
    print tweet['created_at'].encode('utf-8')
    print tweet['coordinates']

stream.statuses.filter(locations='41.8294833,-71.4021500')

'''# Keep going while there are still tweets left
while len(tweets) != 0:
    try:
        tweets = twitter.search(q='',geocode='41.8262,-71.4032,1km',result_type='recent', max_id=tweets['statuses'][len(tweets['statuses'])-1]['id']-1, count=10)
    except TwythonError as e:
        print e

    for tweet in tweets['statuses']:
        print tweet['user']['screen_name'].encode('utf-8')
'''



