from twython import Twython, TwythonError

APP_KEY = 'UQVGvAiVnMSJpqdefj44Jw'
# Acess token generated by twauth.py and hard coded in
ACCESS_TOKEN = 'AAAAAAAAAAAAAAAAAAAAABRMVwAAAAAAnE6%2F41mZ20HV2LVadOufnqih%2Fc8%3DAP8Dhd8DkaKCFhJ1Nn7ZedG5TmU54dRJ865U26ByLgU0oIlkuo'

# Our reference to the twitter api
twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)

# Try to get the first 100 results from twitter
try:
    tweets = twitter.search(q='',geocode='41.8262,-71.4032,1km',result_type='recent', count=100)
except TwythonError as e:
    print e

# Print out the usernames of the tweets
for tweet in tweets['statuses']:
    print tweet['user']['screen_name'].encode('utf-8')

# Keep going while there are still tweets left
while len(tweets) != 0:
    try:
        tweets = twitter.search(q='',geocode='41.8262,-71.4032,1km',result_type='recent', max_id=tweets['statuses'][len(tweets['statuses'])-1]['id']-1, count=100)
    except TwythonError as e:
        print e

    for tweet in tweets['statuses']:
        print tweet['user']['screen_name'].encode('utf-8')



