application: microevents
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: insta.html
  upload: insta.html

- url: /(.*)
  static_files: \1
  upload: (.*)

libraries:
- name: webapp2
  version: "2.5.2"
